export type Region = 'Statewide' | 'Region 1 – Northwest' | 'Region 2 – Missoula' | 'Region 3 – Southwest' | 'Region 4 – Central' | 'Region 5 – Southeast' | 'Region 6 – Northeast' | 'Region 7 – Eastern';
export type ProposalType = 'Conservation' | 'Clarification' | 'Enforcement' | 'Management' | 'Relevancy';
export type Stance = 'Support' | 'Oppose' | 'Modify';

export interface Proposal {
  id: number;
  smAnswerId: string;       // SurveyMonkey dropdown option value (confirmed from scrape)
  title: string;
  regions: Region[];
  type: ProposalType;
  species: string[];
  waterbody: string;
  change: string;           // Plain-language: what the rule actually changes
  rationale: string;        // Why FWP is proposing it (for AI prompt context)
  impact: 'High' | 'Medium' | 'Low';
}

export const PROPOSALS: Proposal[] = [
  {
    id: 1,
    smAnswerId: '1991427552',
    title: 'Definitions of Hook and Bait',
    regions: ['Statewide'],
    type: 'Clarification',
    species: ['All species'],
    waterbody: 'All waters',
    change: 'Adds a formal definition of "hook" and "bait" to the regulations booklet to remove ambiguity about which lure configurations are legal.',
    rationale: 'The current rules leave room for confusion about split-shot rigs, fly-fishing attractors, and scented lures. Clearer definitions reduce enforcement headaches and help anglers stay compliant.',
    impact: 'Low',
  },
  {
    id: 2,
    smAnswerId: '1991427553',
    title: 'Western District Standard Lake Trout Harvest',
    regions: ['Region 1 – Northwest', 'Region 2 – Missoula'],
    type: 'Conservation',
    species: ['Lake trout', 'Bull trout'],
    waterbody: 'Western Montana lakes',
    change: 'Creates a western district standard allowing anglers to keep lake trout beyond the daily limit in their freezer (no possession cap) to encourage aggressive harvest and removal of invasive lake trout.',
    rationale: 'Lake trout introduced to Flathead and Swan Lakes are devastating native bull trout populations. FWP wants anglers to kill as many lake trout as possible, and a possession cap was a barrier to that.',
    impact: 'High',
  },
  {
    id: 3,
    smAnswerId: '1991427554',
    title: 'Western District Standard Smallmouth Bass Harvest Limit',
    regions: ['Region 1 – Northwest', 'Region 2 – Missoula'],
    type: 'Conservation',
    species: ['Smallmouth bass', 'Native fish'],
    waterbody: 'Western Montana rivers and lakes',
    change: 'Establishes a 5-fish daily limit on smallmouth bass in the western district where there is currently no limit, to provide baseline management authority.',
    rationale: 'Smallmouth bass are spreading into native fish habitat in western Montana. A harvest limit signals to anglers that bass are a management priority, not a trophy fish to release.',
    impact: 'Medium',
  },
  {
    id: 4,
    smAnswerId: '1991427555',
    title: 'Eastern District Standard Smallmouth Bass Limits',
    regions: ['Region 6 – Northeast', 'Region 7 – Eastern'],
    type: 'Conservation',
    species: ['Smallmouth bass'],
    waterbody: 'Eastern Montana rivers',
    change: 'Adjusts the smallmouth bass harvest limit in the eastern district to better align with population data and angler use trends.',
    rationale: 'Eastern district bass populations have shifted with increased angler pressure post-pandemic. Updated limits give FWP more management flexibility.',
    impact: 'Medium',
  },
  {
    id: 5,
    smAnswerId: '1991427556',
    title: 'Central District Standard Smallmouth Bass Limits',
    regions: ['Region 4 – Central', 'Region 5 – Southeast'],
    type: 'Conservation',
    species: ['Smallmouth bass'],
    waterbody: 'Central Montana rivers',
    change: 'Establishes or adjusts smallmouth bass harvest limits for central Montana waters to create a consistent management framework.',
    rationale: 'Consistent district standards simplify the regulations booklet and help anglers understand rules without needing to look up each water individually.',
    impact: 'Low',
  },
  {
    id: 6,
    smAnswerId: '1991427557',
    title: 'Transportation of Live Fish in the Eastern District',
    regions: ['Region 6 – Northeast', 'Region 7 – Eastern'],
    type: 'Enforcement',
    species: ['All species'],
    waterbody: 'Eastern Montana waters',
    change: 'Restricts or clarifies rules around transporting live fish between waters in the eastern district to prevent invasive species spread.',
    rationale: 'Live bait transport is a primary pathway for species like carp, goldfish, and invasive minnows to enter new watersheds. Tighter rules reduce that risk.',
    impact: 'Medium',
  },
  {
    id: 7,
    smAnswerId: '1991427559',
    title: 'Crayfish Transportation for Consumption',
    regions: ['Statewide'],
    type: 'Relevancy',
    species: ['Crayfish'],
    waterbody: 'All waters',
    change: 'Clarifies that anglers may legally transport live crayfish from the water where caught if intended for immediate consumption, exempting them from existing live-transport prohibitions.',
    rationale: 'Crayfish are a desirable table food and the current ambiguity in the law has caused unnecessary enforcement friction for people simply taking them home to eat.',
    impact: 'Low',
  },
  {
    id: 8,
    smAnswerId: '1991427560',
    title: 'Including Tiger Trout in Combined Trout Limits',
    regions: ['Region 4 – Central', 'Region 5 – Southeast', 'Region 6 – Northeast', 'Region 7 – Eastern'],
    type: 'Management',
    species: ['Tiger trout', 'Trout'],
    waterbody: 'Central and eastern Montana waters',
    change: 'Adds tiger trout (a brook trout × brown trout hybrid stocked by FWP) into the combined trout daily and possession limit for central and eastern districts.',
    rationale: 'Tiger trout are increasingly stocked in these districts. Leaving them out of the combined limit creates a loophole — this closes it and simplifies accounting for anglers.',
    impact: 'Low',
  },
  {
    id: 9,
    smAnswerId: '1991427561',
    title: 'Flathead Lake Northern Pike Limits',
    regions: ['Region 1 – Northwest'],
    type: 'Conservation',
    species: ['Northern pike', 'Native fish', 'Bull trout'],
    waterbody: 'Flathead Lake',
    change: 'Increases or removes the harvest limit on northern pike in Flathead Lake to encourage aggressive removal of this predatory invasive species.',
    rationale: 'Northern pike in Flathead Lake are a serious threat to the westslope cutthroat, bull trout, and native fish populations. FWP wants anglers to take as many as possible.',
    impact: 'High',
  },
  {
    id: 10,
    smAnswerId: '1991427562',
    title: 'Flathead Lake Rainbow Trout Limits',
    regions: ['Region 1 – Northwest'],
    type: 'Conservation',
    species: ['Rainbow trout'],
    waterbody: 'Flathead Lake',
    change: 'Adjusts the rainbow trout daily limit or size restriction on Flathead Lake to better reflect current population health and angler pressure.',
    rationale: 'Rainbow trout populations in Flathead Lake have shown changes in age structure and abundance. This proposal aims to maintain a sustainable, quality fishery.',
    impact: 'Medium',
  },
  {
    id: 11,
    smAnswerId: '1991427563',
    title: 'Flathead Lake Smallmouth Bass Limits',
    regions: ['Region 1 – Northwest'],
    type: 'Conservation',
    species: ['Smallmouth bass'],
    waterbody: 'Flathead Lake',
    change: 'Establishes a new harvest limit or size restriction on smallmouth bass in Flathead Lake to address their expanding population and impact on native species.',
    rationale: 'Smallmouth bass are establishing in Flathead Lake and threaten native fish. A harvest limit gives FWP a management tool and signals angler responsibility.',
    impact: 'High',
  },
  {
    id: 12,
    smAnswerId: '1991427564',
    title: 'Fishtrap Creek and Tributaries Bait Restriction',
    regions: ['Region 1 – Northwest'],
    type: 'Conservation',
    species: ['Bull trout', 'Westslope cutthroat'],
    waterbody: 'Fishtrap Creek',
    change: 'Restricts fishing to artificial lures only on Fishtrap Creek and its tributaries, prohibiting live and natural bait.',
    rationale: 'Fishtrap Creek supports important bull trout and westslope cutthroat populations. Bait fishing results in higher incidental mortality when fish swallow hooks deeply.',
    impact: 'Medium',
  },
  {
    id: 13,
    smAnswerId: '1991427565',
    title: 'Hungry Horse Reservoir Bull Trout Restriction & Season Change',
    regions: ['Region 1 – Northwest'],
    type: 'Conservation',
    species: ['Bull trout'],
    waterbody: 'Hungry Horse Reservoir',
    change: 'Adds a minimum size limit for bull trout and adjusts the fishing season at Hungry Horse Reservoir to protect the population during critical periods.',
    rationale: 'Bull trout are a federally threatened species. Population surveys show size structure concerns that warrant increased protection at this reservoir.',
    impact: 'High',
  },
  {
    id: 14,
    smAnswerId: '1991427566',
    title: 'Little Bitterroot Lake Kokanee Harvest Limit',
    regions: ['Region 1 – Northwest'],
    type: 'Conservation',
    species: ['Kokanee salmon'],
    waterbody: 'Little Bitterroot Lake',
    change: 'Establishes or modifies the kokanee daily harvest limit at Little Bitterroot Lake based on current population survey data.',
    rationale: 'Kokanee populations fluctuate significantly. Survey data suggest the current limit may be too liberal or too conservative relative to sustainable yield.',
    impact: 'Medium',
  },
  {
    id: 15,
    smAnswerId: '1991427567',
    title: 'Little Bitterroot Lake Rainbow Trout Length Restriction',
    regions: ['Region 1 – Northwest'],
    type: 'Conservation',
    species: ['Rainbow trout'],
    waterbody: 'Little Bitterroot Lake',
    change: 'Adds a minimum length requirement for rainbow trout kept at Little Bitterroot Lake to improve age structure and size quality in the fishery.',
    rationale: 'Angler surveys show dissatisfaction with average fish size. A length limit protects younger fish and allows more to reach a quality size before harvest.',
    impact: 'Medium',
  },
  {
    id: 16,
    smAnswerId: '1991427568',
    title: 'Graves Creek Gear Restriction',
    regions: ['Region 1 – Northwest'],
    type: 'Conservation',
    species: ['Bull trout', 'Westslope cutthroat'],
    waterbody: 'Graves Creek',
    change: 'Restricts Graves Creek to artificial lures or fly fishing only, removing the option to fish with conventional bait rigs.',
    rationale: 'Graves Creek is a small, sensitive tributary supporting native char and cutthroat. Gear restrictions reduce incidental mortality on fish that must be released.',
    impact: 'Medium',
  },
  {
    id: 17,
    smAnswerId: '1991427569',
    title: 'Graves Creek Bait Restriction',
    regions: ['Region 1 – Northwest'],
    type: 'Conservation',
    species: ['Bull trout', 'Westslope cutthroat'],
    waterbody: 'Graves Creek',
    change: 'Prohibits the use of live and scented natural bait on Graves Creek to protect native fish populations in this sensitive drainage.',
    rationale: 'Paired with the gear restriction proposal, this covers the full spectrum of bait types. The two proposals together create a coherent catch-and-release friendly zone.',
    impact: 'Medium',
  },
  {
    id: 18,
    smAnswerId: '1991427570',
    title: 'Vermillion River Bait Restriction',
    regions: ['Region 1 – Northwest'],
    type: 'Conservation',
    species: ['Westslope cutthroat', 'Bull trout'],
    waterbody: 'Vermillion River',
    change: 'Restricts the Vermillion River to artificial lures only, prohibiting the use of natural bait to reduce mortality of native species.',
    rationale: 'The Vermillion River is one of the last strongholds for westslope cutthroat in the region. Bait restrictions reduce deep-hooking mortality in a catch-and-release fishery.',
    impact: 'High',
  },
  {
    id: 19,
    smAnswerId: '1991427571',
    title: 'Vermillion River Gear Restriction',
    regions: ['Region 1 – Northwest'],
    type: 'Conservation',
    species: ['Westslope cutthroat', 'Bull trout'],
    waterbody: 'Vermillion River',
    change: 'Limits gear types allowed on the Vermillion River to single-hook artificial lures and flies to minimize fish injury during catch-and-release.',
    rationale: 'Treble hooks on lures cause significantly more injury to released fish than single hooks. This gear restriction improves post-release survival for native trout.',
    impact: 'High',
  },
  {
    id: 20,
    smAnswerId: '1991427572',
    title: 'Vermillion River Tributary Bait Restriction',
    regions: ['Region 1 – Northwest'],
    type: 'Conservation',
    species: ['Westslope cutthroat', 'Bull trout'],
    waterbody: 'Vermillion River tributaries',
    change: 'Extends the bait restriction from the main Vermillion River to its named tributaries, closing loopholes where anglers could fish bait on feeder creeks.',
    rationale: 'Native fish spawn in tributaries. Protecting the main stem but not the tribs leaves critical habitat unprotected during sensitive life stages.',
    impact: 'Medium',
  },
  {
    id: 21,
    smAnswerId: '1991427573',
    title: 'West Fork Thompson River Bait & Gear Restrictions',
    regions: ['Region 1 – Northwest'],
    type: 'Conservation',
    species: ['Westslope cutthroat', 'Bull trout'],
    waterbody: 'West Fork Thompson River',
    change: 'Restricts the West Fork Thompson River and its tributaries to artificial lures only and removes the option to use natural bait throughout the drainage.',
    rationale: 'This drainage supports a self-sustaining population of native westslope cutthroat and bull trout. Bait and gear restrictions protect these fish from excess mortality.',
    impact: 'High',
  },
  {
    id: 22,
    smAnswerId: '1991427574',
    title: 'McGregor Lake Crayfish Harvest Restriction',
    regions: ['Region 1 – Northwest'],
    type: 'Conservation',
    species: ['Crayfish', 'Native fish'],
    waterbody: 'McGregor Lake',
    change: 'Limits the number of crayfish that can be harvested from McGregor Lake per day or per possession to prevent depletion of this population.',
    rationale: 'Crayfish at McGregor Lake are a forage base for fish species. Unregulated harvest could impact the lake\'s food web and the fish populations anglers value.',
    impact: 'Low',
  },
  {
    id: 23,
    smAnswerId: '1991427575',
    title: 'Racetrack Pond Youth Angler Bait Restriction',
    regions: ['Region 3 – Southwest'],
    type: 'Management',
    species: ['Trout'],
    waterbody: 'Racetrack Pond',
    change: 'Allows anglers 14 and under to use bait at Racetrack Pond while adults remain restricted to artificial lures only, creating a youth-friendly exception.',
    rationale: 'Racetrack Pond is an artificial-lure-only water. This exception recognizes that youth recruitment is a priority — it\'s easier to learn to fish with bait.',
    impact: 'Low',
  },
  {
    id: 24,
    smAnswerId: '1991427576',
    title: 'Warm Springs WMA Season Length',
    regions: ['Region 3 – Southwest'],
    type: 'Management',
    species: ['Trout', 'Warm-water species'],
    waterbody: 'Warm Springs WMA ponds',
    change: 'Extends or adjusts the fishing season at Warm Springs Wildlife Management Area ponds to better match fish population cycles and water conditions.',
    rationale: 'The existing season does not align well with when fish are most healthy and accessible. The adjustment provides better angling opportunity without biological risk.',
    impact: 'Low',
  },
  {
    id: 25,
    smAnswerId: '1991427577',
    title: 'Baker Creek Season Length',
    regions: ['Region 3 – Southwest'],
    type: 'Conservation',
    species: ['Westslope cutthroat'],
    waterbody: 'Baker Creek',
    change: 'Adjusts the opening or closing date of the fishing season on Baker Creek to protect native cutthroat during spawning or low-water periods.',
    rationale: 'Baker Creek is a small tributary where fish are concentrated and vulnerable at certain times of year. A tighter season reduces pressure during these critical windows.',
    impact: 'Low',
  },
  {
    id: 26,
    smAnswerId: '1991427578',
    title: 'Ben Hart Creek Season Length',
    regions: ['Region 3 – Southwest'],
    type: 'Conservation',
    species: ['Westslope cutthroat'],
    waterbody: 'Ben Hart Creek',
    change: 'Modifies the fishing season dates on Ben Hart Creek to better protect native fish during sensitive periods.',
    rationale: 'This small stream has a self-sustaining native cutthroat population that benefits from reduced angling pressure during spawning or early season low flows.',
    impact: 'Low',
  },
  {
    id: 27,
    smAnswerId: '1991427579',
    title: 'Camp Creek Season Length',
    regions: ['Region 3 – Southwest'],
    type: 'Conservation',
    species: ['Westslope cutthroat'],
    waterbody: 'Camp Creek',
    change: 'Adjusts the season opening on Camp Creek to give native fish adequate time to recover from winter conditions before angling pressure begins.',
    rationale: 'Early-season angling on small streams with recovering native trout populations can reduce spawning success. A delayed opener addresses that concern.',
    impact: 'Low',
  },
  {
    id: 28,
    smAnswerId: '1991427580',
    title: 'East Gallatin River Pike Harvest',
    regions: ['Region 3 – Southwest'],
    type: 'Conservation',
    species: ['Northern pike', 'Trout'],
    waterbody: 'East Gallatin River',
    change: 'Establishes a harvest limit on northern pike in the East Gallatin River and closes the river to boat-based fishing to reduce predation on native trout.',
    rationale: 'Northern pike have colonized the East Gallatin and are devastating the trout population. Boat fishing concentrates harvest pressure; removing that option protects river ecology.',
    impact: 'High',
  },
  {
    id: 29,
    smAnswerId: '1991427581',
    title: 'Gallatin River Pike Harvest',
    regions: ['Region 3 – Southwest'],
    type: 'Conservation',
    species: ['Northern pike', 'Trout'],
    waterbody: 'Gallatin River',
    change: 'Adds a northern pike harvest regulation on the Gallatin River to encourage removal of this invasive predator from an important trout fishery.',
    rationale: 'Pike spread from Missouri River tributaries into the Gallatin drainage. Proactive harvest regulations aim to slow this expansion before populations establish.',
    impact: 'High',
  },
  {
    id: 30,
    smAnswerId: '1991427582',
    title: 'Jefferson River Pike Harvest',
    regions: ['Region 3 – Southwest'],
    type: 'Conservation',
    species: ['Northern pike', 'Sauger', 'Trout'],
    waterbody: 'Jefferson River',
    change: 'Adds regulations encouraging pike harvest on the Jefferson River to limit spread of this invasive species in the upper Missouri watershed.',
    rationale: 'The Jefferson River is a corridor for pike expansion. Early management action here can prevent the scale of damage seen downstream in the Missouri system.',
    impact: 'High',
  },
  {
    id: 31,
    smAnswerId: '1991427583',
    title: 'Madison River Pike Harvest & Side Channel Closure',
    regions: ['Region 3 – Southwest'],
    type: 'Conservation',
    species: ['Northern pike', 'Trout'],
    waterbody: 'Madison River',
    change: 'Removes the northern pike no-limit regulation below Ennis Lake AND closes Hyde Creek and Morgan Gulch side channels and areas around islands upstream of Highway 84 bridge year-round to fishing and wading.',
    rationale: 'Pike need no-limit harvest removed to signal harvest priority, while the side channel and island closures protect critical spawning habitat that habitat-enhancement projects have restored.',
    impact: 'High',
  },
  {
    id: 32,
    smAnswerId: '1991427584',
    title: 'Miner Lake Arctic Grayling & Burbot Restrictions',
    regions: ['Region 3 – Southwest'],
    type: 'Conservation',
    species: ['Arctic grayling', 'Burbot'],
    waterbody: 'Miner Lake',
    change: 'Implements catch-and-release only for arctic grayling and adds a harvest restriction on burbot at Miner Lake to protect two species of conservation concern.',
    rationale: 'Arctic grayling are a native Montana species with a very limited range. Burbot at Miner Lake may be competing with grayling. Both regulations protect this unique fishery.',
    impact: 'High',
  },
  {
    id: 33,
    smAnswerId: '1991427585',
    title: 'Missouri River–Big Spring Confluence Season Length',
    regions: ['Region 4 – Central'],
    type: 'Conservation',
    species: ['Trout', 'Sauger'],
    waterbody: 'Missouri River near Big Spring Creek',
    change: 'Modifies the season length at the Missouri River–Big Spring Creek confluence to protect fish during spawning aggregations that concentrate in this spring-fed reach.',
    rationale: 'The spring-fed confluence is a thermal refuge and spawning area. Fish are extremely concentrated and vulnerable; a season closure limits exploitation during this critical time.',
    impact: 'Medium',
  },
  {
    id: 34,
    smAnswerId: '1991427586',
    title: "O'Dell Creek Season Length",
    regions: ['Region 4 – Central'],
    type: 'Conservation',
    species: ['Westslope cutthroat'],
    waterbody: "O'Dell Creek",
    change: "Adjusts the opening date of the fishing season on O'Dell Creek to protect westslope cutthroat trout during early season spawning.",
    rationale: 'Westslope cutthroat spawn in small streams in late spring. Closing O\'Dell Creek until fish have completed spawning reduces disturbance and protects egg survival.',
    impact: 'Low',
  },
  {
    id: 35,
    smAnswerId: '1991427587',
    title: 'Pintler Lake Arctic Grayling Catch-and-Release',
    regions: ['Region 3 – Southwest'],
    type: 'Conservation',
    species: ['Arctic grayling'],
    waterbody: 'Pintler Lake',
    change: 'Designates Pintler Lake as catch-and-release only for arctic grayling, prohibiting harvest of this native species at this high-mountain lake.',
    rationale: 'Arctic grayling populations in isolated high-country lakes are fragile. Any harvest pressure can quickly deplete these self-sustaining populations that take years to recover.',
    impact: 'Medium',
  },
  {
    id: 36,
    smAnswerId: '1991427588',
    title: 'Rae Creek Season Length',
    regions: ['Region 3 – Southwest'],
    type: 'Conservation',
    species: ['Westslope cutthroat'],
    waterbody: 'Rae Creek',
    change: 'Adjusts the fishing season on Rae Creek to align with biological needs of the native cutthroat population and reduce pressure during vulnerable periods.',
    rationale: 'Small tributaries like Rae Creek serve as spawning and rearing habitat. Season adjustments are the most targeted way to protect fish at the most sensitive life stages.',
    impact: 'Low',
  },
  {
    id: 37,
    smAnswerId: '1991427589',
    title: 'Randall Creek Season Length',
    regions: ['Region 4 – Central'],
    type: 'Conservation',
    species: ['Westslope cutthroat'],
    waterbody: 'Randall Creek',
    change: 'Modifies opening and/or closing dates on Randall Creek to protect native trout during spawning migrations.',
    rationale: 'Randall Creek serves as a spawning tributary. A targeted season change protects fish during their most vulnerable period without restricting the broader river system.',
    impact: 'Low',
  },
  {
    id: 38,
    smAnswerId: '1991427590',
    title: 'Red Rock Creek Hybrid Cutthroat Harvest Limit',
    regions: ['Region 3 – Southwest'],
    type: 'Conservation',
    species: ['Cutthroat trout'],
    waterbody: 'Red Rock Creek',
    change: 'Adds a specific harvest limit for hybrid cutthroat trout on Red Rock Creek to manage a population of fish with mixed genetic heritage.',
    rationale: 'FWP has stocked hybrid cutthroat in some waters as a management tool. A harvest limit ensures the fishery remains productive while managing genetic diversity concerns.',
    impact: 'Low',
  },
  {
    id: 39,
    smAnswerId: '1991427591',
    title: 'Thompson Creek Season Length',
    regions: ['Region 1 – Northwest'],
    type: 'Conservation',
    species: ['Westslope cutthroat', 'Bull trout'],
    waterbody: 'Thompson Creek',
    change: 'Adjusts the fishing season on Thompson Creek to protect native fish during spawning and early rearing periods in this northwest Montana drainage.',
    rationale: 'Thompson Creek is a tributary supporting native cutthroat and possibly bull trout. Season restrictions during spawning reduce disturbance and mortality during critical periods.',
    impact: 'Low',
  },
  {
    id: 40,
    smAnswerId: '1991427592',
    title: 'Cow Creek to Beachamp Creek Setline Limit & Season',
    regions: ['Region 6 – Northeast'],
    type: 'Management',
    species: ['Sauger', 'Channel catfish', 'Pallid sturgeon'],
    waterbody: 'Missouri River (Fort Peck area)',
    change: 'Limits the number of setlines (unattended lines) allowed in the Cow Creek to Beachamp Creek reach and adjusts the season they can be used, to reduce conflicts and protect sensitive native species.',
    rationale: 'Setline use has exploded in this reach around the Fred Robinson Bridge. Uncontrolled use crowds out other anglers and poses incidental take risk to pallid sturgeon, a federally endangered species.',
    impact: 'High',
  },
  {
    id: 41,
    smAnswerId: '1991427593',
    title: 'Castle Rock Lake Bluegill Harvest Limit',
    regions: ['Region 7 – Eastern'],
    type: 'Conservation',
    species: ['Bluegill'],
    waterbody: 'Castle Rock Lake (Colstrip)',
    change: 'Limits bluegill harvest to 20 fish daily and in possession from May 15 to June 15 — the spawning season — to protect adult fish concentrated on spawning beds.',
    rationale: 'Post-pandemic angling pressure on Castle Rock Lake has surged. Targeting spawning bluegill on beds is easy and can rapidly deplete a population. A seasonal limit protects the long-term fishery.',
    impact: 'Medium',
  },
];

export const SURVEY_URL = 'https://www.surveymonkey.com/r/BFJ3R9V';
export const EMAIL_FALLBACK = 'fwpfishcomments@mt.gov';
export const DEADLINE = 'May 31, 2026';

export const REGIONS: Region[] = [
  'Statewide',
  'Region 1 – Northwest',
  'Region 2 – Missoula',
  'Region 3 – Southwest',
  'Region 4 – Central',
  'Region 5 – Southeast',
  'Region 6 – Northeast',
  'Region 7 – Eastern',
];

export const REGION_1_PROPOSAL_IDS = [9,10,11,12,13,14,15,16,17,18,19,20,21,22,39];
